import ButtonLink from '@/components/ButtonLink';

export const metadata = {
  title: 'Home page - Create Next App',
  description: 'Generated by create next app',
};

const Home = () => {
  return (
    <>
      <h1 className='text-center text-3xl font-bold uppercase'>Prash Ryuu</h1>
      <p className='mb-8 text-center text-gray-700'>Master & Player</p>
      <p className='mb-8 text-center'>
        ¡Saludos a todos! <br /> Soy Prash Ryuu, un apasionado máster y jugador
        de D&D 5ed. Mi amor por los juegos de rol se despertó con In Nomine
        Satanis, y desde entonces, he explorado emocionantes aventuras en los
        reinos de D&D. Mi personaje estrella es un draconido guerrero,
        fusionando poder y nobleza. ¡Juguemos juntos y creemos historias épicas!{' '}
        <br />
        ¡Nos vemos en la mesa de juego!
        <br /> Prash Ryuu
      </p>

      <div className='text-center'>
        <ButtonLink href='/blog'>Ir al blog</ButtonLink>
      </div>
    </>
  );
};
export default Home;
